version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    platform: linux/amd64   # 👈 THÊM DÒNG NÀY
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 170206
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: